TWEAK_NAME = objcipc
objcipc_FILES = objcipc.m
objcipc_FRAMEWORKS = CoreFoundation Foundation
objcipc_LIBRARIES = objcipc
objcipc_CFLAGS = -I../
objcipc_LDFLAGS = -L../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk